version: "3"
services:
  redis:
    image: redis:7.2.2-bookworm
    ports:
      - "6379:6379"
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
    volumes:
      - "/home/student/data:/data"
    networks:
      - redis-net
  url-shortner:
    image: url-server
    deploy:
      replicas: 4
    ports:
      - "8000:8000"
    networks:
      - redis-net
networks:
  redis-net: