version: "3"
services:
  redis:
    image: 10.128.1.28:5000/redis:latest
    build: redis
    ports:
      - "6379:6379"
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
    volumes:
      - "/home/student/redis-data:/data"
    networks:
      - redis-net

  url-shortner:
    image: 10.128.1.28:5000/shortner:latest
    build: ./shortner
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    networks:
      - redis-net

networks:
  redis-net:
