version: "3"
services:
  redis-master:
    hostname: redis-master
    image: 10.128.1.28:5000/redis:latest
    build: redis
    ports:
      - "6379:6379"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role == manager"
    volumes:
      - "/home/student/redis-data:/data"
    networks:
      - redis-net
  redis-slave:
    hostname: redis-slave
    image: 10.128.1.28:5000/redis:latest
    build: redis
    ports: 
      - "6380:6379"
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "node.role != manager"
    networks:
      - redis-net
      # - webnet
    # healthcheck:
    #   test: ["CMD", "redis-cli", "ping"]
    #   start_period: 20s
    #   interval: 30s
    #   timeout: 10s
    #   retries: 3
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master

  url-shortner:
    image: 10.128.1.28:5000/shortner:latest
    build: ./shortner
    deploy:
      replicas: 4
      restart_policy:
        condition: on-failure
    ports:
      - "8000:8000"
    networks:
      - redis-net

networks:
  redis-net:
