#!/bin/bash
USAGE="Usage: $0 NODE_IP"

if [ "$#" != "1" ]; then
    echo "$USAGE"
    exit 1
fi

NODE_IP="$1"
NODE_NAME="cassandra-node"

ssh student@$NODE_IP "docker container stop $NODE_NAME; docker container rm $NODE_NAME"

echo "Node removed from the cluster."
docker exec -it cassandra-node bash -c "nodetool status"
