#!/bin/bash
# Hosts are retrieved from the "hosts" file. The first host listed is the master.

MASTER=$(head -n 1 ./cassandra/hosts)
NODE_NAME="cassandra-node"
VOLUME_PATH="/home/student/cassandra-data"
CASSANDRA_PORT=9042
REPLICATION_FACTOR=2
KEYSPACE_NAME=url_shortener

# Initialize Cassandra nodes
for host in $(cat ./cassandra/hosts); do
    if [ "$host" = "$MASTER" ]; 
    then
        COMMAND="docker run --name $NODE_NAME -d -e CASSANDRA_BROADCAST_ADDRESS=$host -p 7000:7000 -p $CASSANDRA_PORT:9042 -v $VOLUME_PATH:/var/lib/cassandra cassandra"
    else
        COMMAND="docker run --name $NODE_NAME -d -e CASSANDRA_BROADCAST_ADDRESS=$host -p 7000:7000 -p $CASSANDRA_PORT:9042 -e CASSANDRA_SEEDS=$MASTER -v $VOLUME_PATH:/var/lib/cassandra cassandra"
    fi
    ssh student@$host "docker container stop $NODE_NAME; docker container rm $NODE_NAME; if [ ! -d $VOLUME_PATH ]; then mkdir -p $VOLUME_PATH; fi; $COMMAND;"
    
    while true;
    do
        sleep 5
		STATUS=$(docker exec -it $NODE_NAME nodetool status | grep -e $host)
        STATUSUN=$(echo $STATUS | grep -e "UN")
        echo $STATUS
        [[ ! -z "$STATUSUN" ]] && break;
    done;
    shift
done

# Create keyspace if it doesnt exist
KEYSPACE_EXISTS=$(ssh student@$MASTER "docker exec $NODE_NAME cqlsh -e \"DESCRIBE KEYSPACES;\"" | grep -e "$KEYSPACE_NAME")
if [ -z "$KEYSPACE_EXISTS" ]; then
    ssh student@$MASTER "docker exec $NODE_NAME cqlsh -e \"CREATE KEYSPACE $KEYSPACE_NAME WITH replication = {'class': 'SimpleStrategy', 'replication_factor': $REPLICATION_FACTOR} ; USE $KEYSPACE_NAME; CREATE TABLE IF NOT EXISTS urls (short_code text PRIMARY KEY, url_original text);\""
fi
