#!/bin/bash
# Hosts are retrieved from the "hosts" file. The first host listed is the master.

MASTER=$(head -n 1 ./cassandra/hosts)
NODE_NAME="cassandra-node"

for host in $(cat ./cassandra/hosts); do
	ssh student@$host "docker container stop $NODE_NAME; docker container rm $NODE_NAME"
done
