#!/bin/bash
USAGE="Usage: $0 MASTER_IP IP2 IP3 ..."

if [ "$#" == "0" ]; then
	echo "$USAGE"
	exit 1
fi

MASTER="$1"
NODE_NAME="cassandra-node"

docker container stop $NODE_NAME
docker container rm $NODE_NAME
shift

while (( "$#" )); do
	ssh student@$1 "docker container stop $NODE_NAME; docker container rm $NODE_NAME"
	shift
done
